services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    container_name: ${DB_HOST}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - mongo_qtre:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: mongo_article
      
  backend:
    build: .
    container_name: ${APP_HOST}
    restart: unless-stopped
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
volumes:
  node_modules:
  mongo_qtre: